M48
; DRILL file {KiCad 8.0.6-8.0.6-0~ubuntu24.04.1} date 2024-10-31T19:49:45+0000
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-10-31T19:49:45+00:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6-8.0.6-0~ubuntu24.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1693
%
G90
G05
T1
X3.15Y-3.45
X3.26Y-5.87
X5.405Y-5.965
X5.415Y-3.535
M30
